### ISSUE TITLE
论文内容

### ISSUE THREAD

**Issue by HanAccount** [yangjingqi99/ACM_2022#2]
您好：

我并没有在网上搜索到您的该论文，能麻烦您发一份论文到邮箱吗？

email:  you1120@zut.edu.cn

期待您的回复，谢谢！

**Comment by yangjingqi99** [comment]
> 您好：
> 
> 我并没有在网上搜索到您的该论文，能麻烦您发一份论文到邮箱吗？
> 
> email: [you1120@zut.edu.cn](mailto:you1120@zut.edu.cn)
> 
> 期待您的回复，谢谢！

您好，非常开心您能对我的工作感兴趣，只是这篇文章正在投稿中尚未被接收，等接受之后我一定第一时间发给您！
